### ISSUE TITLE
[fatal] landlock not available

### ISSUE THREAD

**Issue by u9g** [shoenig/ssh-key-sync#49]
Hi, I copied the executable from the releases on github for arm64 to my raspberry pi 4 running ubuntu server but it gives me this output:

```
on@newraspi:~$ ssh-key-sync -github-user u9g
[fatal] landlock not available
```

What's the problem/how can I fix it?

**Comment by shoenig** [comment]
Hi @u9g, sorry about that! I just created a v1.7.1 release which should fix the issue - if it still doesn't work don't hesitate to reopen!

**Comment by u9g** [comment]
Working great now, thanks @shoenig for such a quick fix!
